config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

get 'tasks', to: 'tasks#index'
get 'tasks/new', to: 'tasks#new', as: :newit
post 'tasks', to: 'tasks#create'
delete 'tasks/:id', to: 'tasks#destroy', as: :destroy
get 'tasks/:id', to: 'tasks#show', as: :task
get 'tasks/:id/edit', to: 'tasks#edit', as: :editit
patch 'tasks/:id', to: 'tasks#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    if @task.completed
      @result = "completed"
    else
      @result = "not completed yet"
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Yanone+Kaffeesatz&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/display.html.erb
<div class="container">
  <h1><%= @task.title %></h1>

  <div class="container-details">
    <p> <%= @task.details %></p>
  </div>

  <form action="get">
      <p>
      <%= check_box_tag 'completed', 'done', @task.completed %>
      This task is <%= @result %>
      </p>
  </form>
</div>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="container-title">
    <h1><%= @task.title %></h1>
  </div>

  <div class="form-container">
    <%= form_for(@task, :html => {:class => "form-horizontal center"}) do |f| %>
      <div class="form-group">
        <%= f.label :title, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      </br>
      <div class="form-group">
        <%= f.label :details, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :details, class: "form-control" %>
        </div>
      </div>
      </br>
      <div class="form-group">
        <%= f.label :completed, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.check_box :completed, class: "form-control" %>
        </div>
      </div>
      </br>
      <div class="action">
        <%= f.submit nil, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

</div>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>

  <form action="get">
    <% @tasks.each do |task| %>
      <p>
        <div class="form-group">
        <%= check_box_tag 'completed', 'done', task.completed %>
        <%=link_to "#{task.title}", task_path(task) %>
        <%=link_to destroy_path(task),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class = "fa fa-trash ml-2" aria-hidden="true"></i>
                <% end %>
        </div>
      </p>
    <% end %>
  </form>

</div>

<%= link_to 'Create a task', newit_path %>

app/views/tasks/new.html.erb
<div class="container">
  <div class="container-title">
    <h1>New Task</h1>
  </div>

  <div class="form-container">
    <%= form_for(@task, :html => {:class => "form-horizontal center"}) do |f| %>
      <div class="form-group">
        <%= f.label :title, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>
      </br>
      <div class="form-group">
        <%= f.label :details, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.text_field :details, class: "form-control" %>
        </div>
      </div>
      </br>
      <div class="form-group">
        <%= f.label :completed, class: "col-md-4 control-label" %>
        <div class="col-md-8">
          <%= f.check_box :completed, class: "form-control" %>
        </div>
      </div>
      </br>
        <%= f.submit %>
    <% end %>
  </div>

</div>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<div class="container">
  <div class="container-title">
    <h1><%= @task.title %></h1>
    <%= link_to 'Edit this task', editit_path(@task) %>
  </div>

  <div class="container-details">
    <p> <%= @task.details %></p>
  </div>

  <form action="get">
      <p>
      <%= check_box_tag 'completed', 'done', @task.completed %>
      This task is <%= @result %>
      </p>
  </form>
</div>

<%= link_to 'Back to list', tasks_path %>